version: 2.1
orbs: 
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/work
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
